/*
 * Adam Ventura
 * 02/15/2021
 * This program is a game where a user has to guess a number generated by the computer
 */

package guess_number;

import java.util.Scanner;
import java.util.Random;

public class guess_number {

	public static void main(String[] args) {
		// Create input reader
		Scanner reader = new Scanner(System.in);
		// Create instance of Random class
		Random rand = new Random();
		// Declare Variables
		int iGuess, iAnswer, iLow, iHigh;
		// Generate a number 1 through 20
		iLow = 1;
		iHigh = 21;
		int rand_int = rand.nextInt(iHigh-iLow) + iLow;
		// Prompt user to guess a number and store number in variable iGuess
		System.out.println("Guess a number between 1 and 20: ");
		iGuess = reader.nextInt();
		// Use while loops to keep program running when guess is incorrect
		while (iGuess != rand_int) {
			// Use if statements to give user hints 
			if (iGuess > rand_int) {
				System.out.println("Your guess was too high.");
			}
			if (iGuess < rand_int) {
				System.out.println("Your guess was too low.");
			}
			// Prompt user again for another number
			System.out.println("Guess another between 1 and 20: ");
			iGuess = reader.nextInt();
		}
		// Inform user they guessed correctly and that the game is over
		System.out.println("Congrats! You guessed the number correctly. Game over!");
	}

}
